import logging
from datetime import datetime, timezone, timedelta
from backend.db.repositories.patient_repo import PatientRepository
from backend.db.repositories.report_repo import ReportRepository
from backend.api.schemas import (
    PatientSchema, 
    OmniHealthReportSchema, 
    ECGEvidenceSchema, 
    EchoEvidenceSchema, 
    FusionResultSchema, 
    HistoryAnalysisSchema, 
    FinalAssessmentSchema,
    HistoryRelationship,
    FusionStatus
)

logger = logging.getLogger(__name__)

# 25 Clinical Cases: Exactly 5 cases for each of the 5 doctors (1 Normal Baseline + 4 Distinct Pathologies)
DOCTOR_PATIENT_CASES = [
    # ==========================================
    # DOCTOR 1: Dr. Sanjay Kumar (sanjay@gmail.com / DOC-001) - Interventional Cardiology
    # ==========================================
    {
        "doctor_id": "DOC-001",
        "doctor_email": "sanjay@gmail.com",
        "patient_id": "PT-10483",
        "name": "Marcus Chen",
        "age": 42,
        "gender": "Male",
        "medical_history_summary": "Annual executive screening. Asymptomatic marathon runner with normal cardiovascular baseline.",
        "report_id": "REP-10483",
        "assessment_date": datetime.now(timezone.utc) - timedelta(hours=3),
        "ecg_finding": "Normal Sinus Rhythm (68 bpm) with normal P-wave axis, PR interval (154 ms), narrow QRS (88 ms), and isoelectric ST segments.",
        "ecg_conf": 0.98,
        "ecg_evidence": ["Heart rate: 68 bpm (Normal regular)", "PR interval: 154 ms, QRS: 88 ms, QTc: 412 ms", "No ischemic ST-T abnormalities or pathological Q waves"],
        "echo_finding": "Preserved left ventricular systolic function with LVEF 62%. Normal left ventricular chamber dimensions and global wall motion.",
        "echo_conf": 0.96,
        "lvef": 62.0,
        "echo_evidence": ["Estimated LVEF: 62.0% (Preserved, Normal)", "LV internal dimension in diastole (LVEDD): 48 mm (Normal)", "Interventricular septum: 9.5 mm (Normal thickness)", "Normal biventricular contractility with no regional wall motion defects"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant normal baseline: Normal 12-lead electrical conduction corroborates fully preserved mechanical pump performance (LVEF 62%).",
        "hist_rel": HistoryRelationship.SIMILAR,
        "hist_summary": "Completely stable normal cardiac evaluation. No cardiovascular pathology detected.",
        "hist_changes": [],
        "hist_persistent": ["Normal sinus rhythm", "Normal LVEF (62%)"],
        "hist_new": [],
        "final_primary": "Normal Cardiac Evaluation — Normal Sinus Rhythm with Preserved Left Ventricular Systolic Function (LVEF 62%).",
        "final_plan": "Reassure patient. Continue routine physical fitness training and scheduled age-appropriate wellness follow-up in 12 months."
    },
    {
        "doctor_id": "DOC-001",
        "doctor_email": "sanjay@gmail.com",
        "patient_id": "PT-10482",
        "name": "Eleanor Vance",
        "age": 64,
        "gender": "Female",
        "medical_history_summary": "Hypertension, hyperlipidemia. Presented with acute retrosternal crushing chest pain radiating to left jaw (3 hours duration).",
        "report_id": "REP-10482",
        "assessment_date": datetime.now(timezone.utc) - timedelta(hours=2),
        "ecg_finding": "Sinus rhythm (94 bpm) with marked ST-segment elevation in leads V1-V4 (up to 4.1 mm) with reciprocal inferior ST depression (II, III, aVF). Acute anterior STEMI pattern.",
        "ecg_conf": 0.96,
        "ecg_evidence": ["ST elevation in V1: 2.8 mm, V2: 4.1 mm, V3: 3.6 mm, V4: 2.2 mm", "Reciprocal ST depression in III & aVF (>1.5 mm)", "Developing pathological Q-waves in V2-V3"],
        "echo_finding": "Severely reduced left ventricular systolic function with LVEF 33%. Severe apical cap akinesis and anterior-septal hypokinesia.",
        "echo_conf": 0.94,
        "lvef": 33.0,
        "echo_evidence": ["Estimated LVEF: 33.0% (Severely Reduced, HFrEF)", "Wall Motion Score Index (WMSI): 2.15", "Apical cap akinesis and anterior interventricular septal hypokinesia", "Preserved basal wall thickening"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant LAD territory acute transmural infarction: Electrophysiological ST elevation corresponds directly to mechanical apical akinesis.",
        "hist_rel": HistoryRelationship.NEW,
        "hist_summary": "Acute catastrophic change from normal baseline 6 months prior to acute anterior STEMI with LVEF drop from 60% to 33%.",
        "hist_changes": ["New ST elevation V1-V4", "New apical akinesis", "LVEF drop of 27%"],
        "hist_persistent": [],
        "hist_new": ["Acute Anterior STEMI", "HFrEF (LVEF 33%)", "Apical Akinesis"],
        "final_primary": "Acute Anterior ST-Elevation Myocardial Infarction (STEMI) with Resultant Acute Systolic Dysfunction (LVEF 33%) and Apical Akinesis.",
        "final_plan": "Immediate emergent primary percutaneous coronary intervention (PPCI) of the proximal LAD. Dual antiplatelet therapy (DAPT), high-intensity statin, and guideline-directed medical therapy."
    },
    {
        "doctor_id": "DOC-001",
        "doctor_email": "sanjay@gmail.com",
        "patient_id": "PT-10487",
        "name": "David Miller",
        "age": 67,
        "gender": "Male",
        "medical_history_summary": "Type 2 diabetes, 40 pack-year smoking. Presented with 4 hours of diaphoresis, nausea, and severe epigastric burning radiating to back.",
        "report_id": "REP-10487",
        "assessment_date": datetime.now(timezone.utc) - timedelta(hours=4),
        "ecg_finding": "Convex ST-segment elevation in leads II, III, aVF (2.5-3.2 mm) and V5-V6 with reciprocal ST depression in lead aVL (2.1 mm). Inferolateral STEMI.",
        "ecg_conf": 0.94,
        "ecg_evidence": ["ST elevation in II: 2.5 mm, III: 3.2 mm, aVF: 2.8 mm", "Lateral lead ST elevation in V5-V6 (1.8 mm)", "Reciprocal ST depression in aVL (2.1 mm)"],
        "echo_finding": "Moderately reduced left ventricular systolic function with LVEF 42%. Basal and mid-inferior/lateral wall akinesis in LCx/RCA territory.",
        "echo_conf": 0.91,
        "lvef": 42.0,
        "echo_evidence": ["Estimated LVEF: 42.0% (Moderately Reduced)", "Basal-inferior and lateral wall akinesis", "Compensatory hyperkinesis of anterior-apical segments"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant inferolateral myocardial infarction: Inferior/lateral ST elevation aligns with basal-inferior akinesis.",
        "hist_rel": HistoryRelationship.NEW,
        "hist_summary": "Acute ischemic presentation with new inferior STEMI and new regional wall motion abnormalities.",
        "hist_changes": ["New inferior ST elevation", "New inferior wall akinesis"],
        "hist_persistent": [],
        "hist_new": ["Acute Inferolateral STEMI", "Basal-Inferior Akinesis"],
        "final_primary": "Acute Inferolateral STEMI with Basal-Inferior Akinesis and Moderately Reduced LVEF (42%).",
        "final_plan": "Emergency cardiac catheterization with coronary angiography for RCA/LCx culprit lesion revascularization. Initiate heparin infusion and DAPT."
    },
    {
        "doctor_id": "DOC-001",
        "doctor_email": "sanjay@gmail.com",
        "patient_id": "PT-10485",
        "name": "Robert Kowalski",
        "age": 58,
        "gender": "Male",
        "medical_history_summary": "15-year history of poorly controlled hypertension and smoking. Intermittent atypical exertional chest heaviness.",
        "report_id": "REP-10485",
        "assessment_date": datetime.now(timezone.utc) - timedelta(days=1),
        "ecg_finding": "High-voltage Left Ventricular Hypertrophy (Sokolow-Lyon 4.1 mV) with lateral repolarization strain and pathological Q-waves in leads III & aVF.",
        "ecg_conf": 0.92,
        "ecg_evidence": ["Sokolow-Lyon index (SV1 + RV5): 4.1 mV (>3.5 mV diagnostic)", "Pathological Q-waves in III and aVF (>0.04s duration)", "Asymmetric T-wave inversion in V5-V6 (LV strain)"],
        "echo_finding": "Concentric left ventricular hypertrophy (septum 14.5 mm, posterior wall 13.8 mm) with preserved LVEF (56%) and basal-inferior hypokinesis.",
        "echo_conf": 0.93,
        "lvef": 56.0,
        "echo_evidence": ["Estimated LVEF: 56.0% (Preserved)", "Interventricular septal thickness: 14.5 mm (Concentric LVH)", "Posterior wall thickness: 13.8 mm", "Localized basal-inferior wall thinning and hypokinesis"],
        "fusion_status": FusionStatus.COMPLEMENTARY,
        "fusion_summary": "Complementary chronic electrical and structural findings: High-voltage strain matches concentric LV wall thickening; inferior Q-waves align with localized scar.",
        "hist_rel": HistoryRelationship.PERSISTENT,
        "hist_summary": "Known chronic hypertensive heart disease with established concentric remodeling and prior silent inferior infarction.",
        "hist_changes": ["Slight progression of LV wall thickness (+1.2 mm)"],
        "hist_persistent": ["Concentric LVH", "Prior inferior Q-waves"],
        "hist_new": [],
        "final_primary": "Concentric Left Ventricular Hypertrophy with Lateral Strain and Prior Silent Inferior Myocardial Infarction.",
        "final_plan": "Intensify antihypertensive therapy with ACE-inhibitor (Ramipril) and calcium channel blocker (Amlodipine). Schedule stress myocardial perfusion imaging."
    },
    {
        "doctor_id": "DOC-001",
        "doctor_email": "sanjay@gmail.com",
        "patient_id": "PT-10492",
        "name": "Arthur Pendelton",
        "age": 74,
        "gender": "Male",
        "medical_history_summary": "Prior extensive anterior MI 3 years ago. Presented with exertional dyspnea and transient right-sided weakness (TIA).",
        "report_id": "REP-10492",
        "assessment_date": datetime.now(timezone.utc) - timedelta(days=2),
        "ecg_finding": "Persistent ST-segment elevation (>2.5 mm in V1-V4) with deep pathological Q-waves (QS pattern in V1-V3), diagnostic of chronic LV aneurysm.",
        "ecg_conf": 0.95,
        "ecg_evidence": ["Persistent ST elevation V1-V4 unchanged from discharge 6 months ago", "QS complex in V1-V3 with loss of anterior R-waves", "Low precordial voltage transition"],
        "echo_finding": "Severely dilated, dyskinetic apical left ventricular aneurysm with a distinct 18x12 mm mural thrombus. Severely reduced LVEF (26%).",
        "echo_conf": 0.94,
        "lvef": 26.0,
        "echo_evidence": ["Estimated LVEF: 26.0% (Severe Ischemic Cardiomyopathy)", "Large apical outpouching with paradoxical systolic dyskinesia", "Echogenic 18x12 mm layered mural thrombus adhering to apical cap", "Spontaneous echo contrast (smoke) in LV cavity"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant chronic aneurysm morphology: Persistent anterior ST elevation directly confirms the anatomical dyskinetic aneurysm with apical clot.",
        "hist_rel": HistoryRelationship.CHANGED,
        "hist_summary": "Known chronic anterior aneurysm with new development of apical mural thrombus, providing source for cerebral embolic TIA.",
        "hist_changes": ["New 18x12 mm mural thrombus in apex", "LVEF slightly reduced from 30% to 26%"],
        "hist_persistent": ["Apical aneurysm", "Persistent ST elevation"],
        "hist_new": ["Left Ventricular Mural Thrombus", "Cardioembolic TIA Risk"],
        "final_primary": "Chronic Apical Left Ventricular Aneurysm with Severe Ischemic Cardiomyopathy (LVEF 26%) and Active Apical Mural Thrombus.",
        "final_plan": "Initiate therapeutic systemic anticoagulation with Warfarin (INR goal 2.0-3.0) or NOAC. Optimize heart failure quadruple therapy (ARNI, Beta-blocker, MRA, SGLT2i). Consider surgical aneurysmectomy evaluation."
    },

    # ==========================================
    # DOCTOR 2: Dr. Arun Mohan (arun@gmail.com / DOC-002) - Cardiac Electrophysiology & Arrhythmias
    # ==========================================
    {
        "doctor_id": "DOC-002",
        "doctor_email": "arun@gmail.com",
        "patient_id": "PT-10501",
        "name": "Maya Lin",
        "age": 35,
        "gender": "Female",
        "medical_history_summary": "Pre-operative cardiac clearance for elective orthopedics. Completely asymptomatic with regular rhythm.",
        "report_id": "REP-10501",
        "assessment_date": datetime.now(timezone.utc) - timedelta(hours=5),
        "ecg_finding": "Normal Resting Sinus Rhythm (64 bpm) with normal P-wave morphology, normal PR (146 ms), normal QRS duration (84 ms), and normal QTc (398 ms).",
        "ecg_conf": 0.99,
        "ecg_evidence": ["Resting heart rate: 64 bpm", "Normal intervals: PR 146 ms, QRS 84 ms, QTc 398 ms", "Isoelectric baseline across all 12 leads"],
        "echo_finding": "Normal left ventricular systolic function with LVEF 64%. Normal chamber sizes and preserved biventricular kinematics.",
        "echo_conf": 0.97,
        "lvef": 64.0,
        "echo_evidence": ["Estimated LVEF: 64.0% (Preserved)", "Normal left atrial volume index (LAVI 24 ml/m2)", "Normal valvular structure without regurgitation"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant normal electrophysiology and mechanics: Normal sinus electrical axis matches normal chamber contractility.",
        "hist_rel": HistoryRelationship.SIMILAR,
        "hist_summary": "Stable normal cardiac evaluation with zero electrophysiological or mechanical abnormalities.",
        "hist_changes": [],
        "hist_persistent": ["Normal sinus rhythm"],
        "hist_new": [],
        "final_primary": "Normal Electrophysiological & Structural Cardiac Assessment (LVEF 64%).",
        "final_plan": "Full preoperative cardiovascular clearance approved. No electrophysiological intervention required."
    },
    {
        "doctor_id": "DOC-002",
        "doctor_email": "arun@gmail.com",
        "patient_id": "PT-10484",
        "name": "Sarah Jenkins",
        "age": 71,
        "gender": "Female",
        "medical_history_summary": "Paroxysmal Atrial Fibrillation, hypertension. Presented with sudden-onset palpitations, lightheadedness, and exertional fatigue.",
        "report_id": "REP-10484",
        "assessment_date": datetime.now(timezone.utc) - timedelta(hours=6),
        "ecg_finding": "Atrial Fibrillation with Rapid Ventricular Response (124 bpm), absent discrete P waves, irregular fibrillatory 'f' waves, and variable RR intervals.",
        "ecg_conf": 0.95,
        "ecg_evidence": ["Irregularly irregular ventricular response rate: 118-134 bpm (mean 124 bpm)", "Absent P-waves with fine baseline fibrillatory oscillations", "Rate-related non-specific ST-segment sagging"],
        "echo_finding": "Mildly reduced left ventricular systolic function (LVEF 48%) with moderate Left Atrial Enlargement (LAVI 44 ml/m2) and beat-to-beat stroke volume variation.",
        "echo_conf": 0.91,
        "lvef": 48.0,
        "echo_evidence": ["Estimated LVEF: 48.0% (Mild Tachycardia-Induced Dysfunction)", "Moderate left atrial dilatation (LAVI: 44 ml/m2)", "Absence of mitral A-wave on pulsed Doppler confirming atrial standstill"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant supraventricular arrhythmia: Atrial electrical fibrillation directly matches loss of mechanical atrial kick and dilated left atrium.",
        "hist_rel": HistoryRelationship.CHANGED,
        "hist_summary": "Progression from paroxysmal to persistent rapid atrial fibrillation with mild secondary systolic blunting.",
        "hist_changes": ["Rate increased from baseline 72 bpm to 124 bpm", "Mild LVEF decline from 55% to 48%", "Left atrial enlargement"],
        "hist_persistent": [],
        "hist_new": ["AFib with RVR", "Tachycardiomyopathy early changes"],
        "final_primary": "Atrial Fibrillation with Rapid Ventricular Response (124 bpm), Moderate Left Atrial Dilatation, and Mild Systolic Blunting (LVEF 48%).",
        "final_plan": "Rate control with IV/oral Beta-blocker (Metoprolol succinate) or Diltiazem. Calculate CHA2DS2-VASc score (=4, female, age >65, HTN) and initiate oral anticoagulation (Apixaban 5mg BID). Plan for elective catheter pulmonary vein isolation (PVI) ablation."
    },
    {
        "doctor_id": "DOC-002",
        "doctor_email": "arun@gmail.com",
        "patient_id": "PT-10491",
        "name": "Carlos Morales",
        "age": 61,
        "gender": "Male",
        "medical_history_summary": "Prior CABG and anterior MI. Presenting with sudden-onset sustained rapid palpitations, dizziness, and diaphoresis.",
        "report_id": "REP-10491",
        "assessment_date": datetime.now(timezone.utc) - timedelta(hours=1),
        "ecg_finding": "Sustained Monomorphic Ventricular Tachycardia at 165 bpm with wide QRS complex (170 ms), positive precordial concordance, and AV dissociation with capture beats.",
        "ecg_conf": 0.97,
        "ecg_evidence": ["Wide regular complex tachycardia at 165 bpm (QRS width: 170 ms)", "AV dissociation with visible independent P-waves", "Fusion beats and positive precordial concordance (V1-V6)"],
        "echo_finding": "Severely reduced left ventricular systolic function (LVEF 30%) with extensive anterior and apical wall thinning, akinesis, and ventricular dyssynchrony.",
        "echo_conf": 0.93,
        "lvef": 30.0,
        "echo_evidence": ["Estimated LVEF: 30.0% (Severe Ischemic Heart Failure)", "Extensive anterior myocardial scar and thinning (6 mm)", "Marked electromechanical dyssynchrony during tachycardia"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant scar-related reentrant ventricular tachycardia: Anterior myocardial infarct scar provides physical substrate for monomorphic VT circuit.",
        "hist_rel": HistoryRelationship.NEW,
        "hist_summary": "New presentation of life-threatening sustained monomorphic ventricular tachycardia in the setting of chronic ischemic scar.",
        "hist_changes": ["New monomorphic VT rhythm", "Hemodynamic instability"],
        "hist_persistent": ["Chronic anterior scar", "Severe systolic failure"],
        "hist_new": ["Sustained Monomorphic VT", "Malignant Arrhythmia Substrate"],
        "final_primary": "Sustained Monomorphic Ventricular Tachycardia (165 bpm) Secondary to Chronic Post-Infarct Anterior Myocardial Scar (LVEF 30%).",
        "final_plan": "Emergency synchronized electrical cardioversion if unstable or IV Amiodarone loading. Emergent admission to CCU, urgent electrophysiology 3D electroanatomical mapping & catheter scar ablation, and primary secondary-prevention Dual-Chamber Implantable Cardioverter-Defibrillator (ICD) placement."
    },
    {
        "doctor_id": "DOC-002",
        "doctor_email": "arun@gmail.com",
        "patient_id": "PT-10495",
        "name": "Henry Thorne",
        "age": 81,
        "gender": "Male",
        "medical_history_summary": "Presenting after sudden unprovoked drop attack / syncope (Stokes-Adams attack) while walking. Profound bradycardia on admission.",
        "report_id": "REP-10495",
        "assessment_date": datetime.now(timezone.utc) - timedelta(hours=8),
        "ecg_finding": "Complete (3rd-Degree) Atrioventricular Block with complete AV dissociation: Atrial rate 88 bpm (sinus P-waves), ventricular escape rate 36 bpm (wide QRS 148 ms).",
        "ecg_conf": 0.98,
        "ecg_evidence": ["Complete AV dissociation: P waves march out at 88 bpm with no relationship to QRS", "Ventricular escape rhythm at 36 bpm with right bundle branch morphology", "Prolonged ventricular asystolic pauses up to 3.8 seconds"],
        "echo_finding": "Preserved intrinsic left ventricular systolic function (LVEF 54%) with normal chamber volumes and extensive calcification of the aortic and mitral annulus.",
        "echo_conf": 0.92,
        "lvef": 54.0,
        "echo_evidence": ["Estimated LVEF: 54.0% (Preserved intrinsic contractility)", "Severe calcification of central fibrous body and aorto-mitral curtain", "Normal LV dimensions with high stroke volume per beat (compensatory)"],
        "fusion_status": FusionStatus.COMPLEMENTARY,
        "fusion_summary": "Complementary conduction failure: Isolated electrical AV conduction block in the presence of preserved mechanical myocardial pumping function.",
        "hist_rel": HistoryRelationship.CHANGED,
        "hist_summary": "Progression from prior first-degree AV block and bifascicular block to complete third-degree AV block with Stokes-Adams syncope.",
        "hist_changes": ["Complete AV block", "Escape rate 36 bpm", "Asystolic pauses"],
        "hist_persistent": [],
        "hist_new": ["Complete 3rd-Degree AV Block", "Stokes-Adams Syndrome"],
        "final_primary": "Complete (3rd-Degree) Atrioventricular Block with Symptomatic Stokes-Adams Syncope and Preserved Systolic Function (LVEF 54%).",
        "final_plan": "Immediate temporary transcutaneous / transvenous pacing support. Schedule emergent permanent dual-chamber (DDD) pacemaker implantation. Discontinue any AV nodal blocking agents."
    },
    {
        "doctor_id": "DOC-002",
        "doctor_email": "arun@gmail.com",
        "patient_id": "PT-10486",
        "name": "Amina Diallo",
        "age": 49,
        "gender": "Female",
        "medical_history_summary": "NYHA Class III heart failure, progressive orthopnea, and lower extremity edema over 4 months.",
        "report_id": "REP-10486",
        "assessment_date": datetime.now(timezone.utc) - timedelta(days=1),
        "ecg_finding": "Sinus rhythm (82 bpm) with wide QRS (164 ms) Complete Left Bundle Branch Block (LBBB) morphology with broad notched R-waves in I, aVL, V6 and deep QS in V1-V2.",
        "ecg_conf": 0.96,
        "ecg_evidence": ["QRS duration: 164 ms (>150 ms CRT criteria positive)", "Notched 'M-shaped' R-waves in lateral leads I, aVL, V6", "Absence of septal Q-waves in lateral leads"],
        "echo_finding": "Severely dilated left ventricle (LVEDD 66 mm) with severely reduced LVEF (28%), pronounced septal flash, and electromechanical dyssynchrony.",
        "echo_conf": 0.94,
        "lvef": 28.0,
        "echo_evidence": ["Estimated LVEF: 28.0% (Severely Reduced, Non-Ischemic DCM)", "Marked left ventricular dilation (LVEDD 66 mm, LVESD 56 mm)", "Pronounced septal flash and apical rocking (dyssynchrony)", "Moderate functional mitral regurgitation"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant electromechanical dyssynchrony: Electrical LBBB with QRS 164ms directly drives mechanical septal flash and delayed lateral wall activation.",
        "hist_rel": HistoryRelationship.PERSISTENT,
        "hist_summary": "Persistent dilated cardiomyopathy with refractory heart failure symptoms despite optimal oral medical therapy.",
        "hist_changes": ["QRS widening from 148 ms to 164 ms"],
        "hist_persistent": ["Severe LV dilation", "Reduced LVEF (28%)", "Complete LBBB"],
        "hist_new": [],
        "final_primary": "Non-Ischemic Dilated Cardiomyopathy with Complete LBBB (QRS 164 ms), Severe Dyssynchrony, and Severe Systolic Failure (LVEF 28%).",
        "final_plan": "Class I guideline indication for Cardiac Resynchronization Therapy with Defibrillator (CRT-D). Optimize guideline-directed medical therapy (GDMT: Sacubitril/Valsartan, Carvedilol, Spironolactone, Dapagliflozin)."
    },

    # ==========================================
    # DOCTOR 3: Dr. Raman Sundaram (raman@gmail.com / DOC-003) - Advanced Cardiac Imaging
    # ==========================================
    {
        "doctor_id": "DOC-003",
        "doctor_email": "raman@gmail.com",
        "patient_id": "PT-10502",
        "name": "Lucas Vance",
        "age": 45,
        "gender": "Male",
        "medical_history_summary": "Routine imaging health check. Preserved exercise tolerance, no cardiac symptoms.",
        "report_id": "REP-10502",
        "assessment_date": datetime.now(timezone.utc) - timedelta(hours=4),
        "ecg_finding": "Normal Sinus Rhythm (70 bpm) with normal axis, normal voltage criteria, and normal repolarization.",
        "ecg_conf": 0.98,
        "ecg_evidence": ["Heart rate: 70 bpm, PR: 152 ms, QRS: 86 ms", "No hypertrophy or ischemia"],
        "echo_finding": "Normal 3D echocardiographic speckle strain (GLS -21.4%) with preserved LVEF (60%), normal wall thickness (9.2 mm), and normal valvular flow.",
        "echo_conf": 0.96,
        "lvef": 60.0,
        "echo_evidence": ["Estimated LVEF: 60.0% (Preserved)", "Global Longitudinal Strain (GLS): -21.4% (Normal > -18%)", "Diastolic E/A ratio 1.3, E/e' 6.8 (Normal filling pressures)", "Normal 3D chamber volumes"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant normal multimodal imaging: Preserved electrical parameters align with optimal myocardial strain kinematics.",
        "hist_rel": HistoryRelationship.SIMILAR,
        "hist_summary": "Completely normal advanced cardiac imaging evaluation.",
        "hist_changes": [],
        "hist_persistent": ["Normal strain", "Normal LVEF"],
        "hist_new": [],
        "final_primary": "Normal Advanced Cardiac Imaging & Strain Analysis (LVEF 60%, GLS -21.4%).",
        "final_plan": "Reassure patient. Normal myocardial contractility and strain profile confirmed."
    },
    {
        "doctor_id": "DOC-003",
        "doctor_email": "raman@gmail.com",
        "patient_id": "PT-10488",
        "name": "Sofia Rossi",
        "age": 38,
        "gender": "Female",
        "medical_history_summary": "Exertional presyncope, dyspnea, and a harsh 3/6 mid-systolic ejection murmur along the left sternal border.",
        "report_id": "REP-10488",
        "assessment_date": datetime.now(timezone.utc) - timedelta(days=1),
        "ecg_finding": "Sinus rhythm (74 bpm) with marked LVH voltage criteria and deep, narrow, dagger-like septal Q-waves in lateral leads I, aVL, V5, V6.",
        "ecg_conf": 0.93,
        "ecg_evidence": ["Deep narrow dagger Q-waves in lateral leads (<30 ms duration, >3 mm depth)", "Sokolow-Lyon voltage > 4.2 mV", "Prominent high precordial voltages V2-V5"],
        "echo_finding": "Hyperdynamic left ventricular systolic function (LVEF 72%) with severe Asymmetric Septal Hypertrophy (IVS 22 mm vs PW 11 mm) and Systolic Anterior Motion (SAM) of mitral leaflet.",
        "echo_conf": 0.96,
        "lvef": 72.0,
        "echo_evidence": ["Estimated LVEF: 72.0% (Hyperdynamic, Preserved)", "Interventricular septal thickness (IVS): 22.0 mm (Severe Asymmetric Hypertrophy)", "Septal-to-posterior wall thickness ratio: 2.0 (>1.3 diagnostic)", "Systolic Anterior Motion (SAM) of mitral leaflet with dynamic LVOT peak gradient 68 mmHg"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant genetic/structural agreement: Deep dagger-like lateral Q-waves reflect asymmetric septal hypertrophy; hyperdynamic cavity obliteration corroborates high LVEF and dynamic LVOT obstruction.",
        "hist_rel": HistoryRelationship.NEW,
        "hist_summary": "Classic presentation of Hypertrophic Obstructive Cardiomyopathy (HOCM) in a young adult.",
        "hist_changes": ["Severe septal hypertrophy (22 mm)", "Dagger Q waves", "Dynamic LVOT gradient"],
        "hist_persistent": [],
        "hist_new": ["HOCM", "Dynamic LVOT Obstruction", "Systolic Anterior Motion (SAM)"],
        "final_primary": "Hypertrophic Obstructive Cardiomyopathy (HOCM) with Severe Asymmetric Septal Hypertrophy (22 mm), Systolic Anterior Motion (SAM), and Dynamic LVOT Gradient (68 mmHg).",
        "final_plan": "Initiate beta-blocker therapy (Metoprolol succinate) or selective cardiac myosin inhibitor (Mavacamten). Avoid vasodilators and diuretics. Refer for Cardiac MRI and sudden cardiac death (SCD) risk stratification."
    },
    {
        "doctor_id": "DOC-003",
        "doctor_email": "raman@gmail.com",
        "patient_id": "PT-10496",
        "name": "Yuki Tanaka",
        "age": 70,
        "gender": "Male",
        "medical_history_summary": "Bilateral carpal tunnel syndrome, spinal stenosis, progressive exertional dyspnea, ascites, and lower extremity pitting edema.",
        "report_id": "REP-10496",
        "assessment_date": datetime.now(timezone.utc) - timedelta(days=2),
        "ecg_finding": "Low voltage QRS complexes in limb leads (<0.5 mV) with pseudo-infarction pattern (QS in V1-V3) strikingly discordant with structural hypertrophy.",
        "ecg_conf": 0.94,
        "ecg_evidence": ["Limb lead QRS amplitude < 0.5 mV throughout leads I, II, III, aVR, aVL, aVF", "Pseudo-infarct QS pattern across V1-V3 without prior CAD", "First-degree AV block (PR 218 ms)"],
        "echo_finding": "Severe concentric biventricular wall thickening (16.5 mm) with characteristic granular 'sparkling' ground-glass myocardial texture, apical sparing strain ('cherry on top'), and reduced LVEF (44%).",
        "echo_conf": 0.95,
        "lvef": 44.0,
        "echo_evidence": ["Estimated LVEF: 44.0% (Restrictive Cardiomyopathy Pattern)", "Interventricular septum: 16.5 mm, Posterior wall: 15.8 mm ('Sparkling' myocardium)", "Strain Bullseye: Severe basal and mid-ventricular impairment with preserved apical strain (Apical Sparing / Cherry on Top)", "Restrictive filling pattern (E/A 2.6, deceleration time 120 ms, biatrial enlargement)"],
        "fusion_status": FusionStatus.COMPLEMENTARY,
        "fusion_summary": "Pathognomonic Amyloidosis discordance: Low electrical voltage on ECG directly contradicts marked structural myocardial wall thickening (16.5 mm) on echocardiography.",
        "hist_rel": HistoryRelationship.NEW,
        "hist_summary": "Newly diagnosed infiltrative cardiac amyloidosis with characteristic electrical-structural dissociation.",
        "hist_changes": ["Biventricular thickening", "Apical sparing strain", "Low ECG voltage"],
        "hist_persistent": [],
        "hist_new": ["Cardiac Amyloidosis (ATTR/AL)", "Restrictive Cardiomyopathy"],
        "final_primary": "Infiltrative Cardiac Amyloidosis with Restrictive Cardiomyopathy, Characteristic Apical Sparing Strain Pattern, and Electrical-Structural Voltage Discordance.",
        "final_plan": "Order serum/urine immunofixation electrophoresis and free light chains (to rule out AL amyloidosis) plus Technetium-99m Pyrophosphate (99mTc-PYP) scintigraphy scan for ATTR amyloidosis. Initiate Tafamidis therapy if ATTR-positive."
    },
    {
        "doctor_id": "DOC-003",
        "doctor_email": "raman@gmail.com",
        "patient_id": "PT-10489",
        "name": "James Wilson",
        "age": 78,
        "gender": "Male",
        "medical_history_summary": "Progressive exertional dyspnea, angina, and near-syncope when walking uphill over 6 months.",
        "report_id": "REP-10489",
        "assessment_date": datetime.now(timezone.utc) - timedelta(days=3),
        "ecg_finding": "Left ventricular hypertrophy with prominent repolarization strain pattern (ST depression and T-wave inversion in leads V4-V6).",
        "ecg_conf": 0.91,
        "ecg_evidence": ["Sokolow-Lyon voltage > 3.8 mV", "Lateral lead ST-segment depression with asymmetric T-wave inversion", "Left atrial abnormality criteria (bifid P-wave in lead II)"],
        "echo_finding": "Severely calcified, heavily restricted aortic valve leaflets with Aortic Valve Area (AVA) 0.7 cm2, peak transaortic velocity 4.4 m/s, mean pressure gradient 46 mmHg, and concentric LV remodeling (LVEF 52%).",
        "echo_conf": 0.97,
        "lvef": 52.0,
        "echo_evidence": ["Estimated LVEF: 52.0% (Preserved/Normal)", "Aortic Valve Area (Continuity Equation): 0.7 cm2 (<1.0 cm2 severe)", "Peak transvalvular velocity: 4.4 m/s (>4.0 m/s severe)", "Mean pressure gradient: 46 mmHg (>40 mmHg severe)", "Concentric LV hypertrophy with septal thickness 14 mm"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant severe aortic stenosis: Valvular high-gradient pressure overload directly correlates with secondary electrical LV strain pattern.",
        "hist_rel": HistoryRelationship.CHANGED,
        "hist_summary": "Progression from moderate aortic stenosis (AVA 1.3 cm2) 2 years ago to severe symptomatic calcific aortic stenosis.",
        "hist_changes": ["AVA reduced from 1.3 to 0.7 cm2", "Peak velocity increased to 4.4 m/s", "Mean gradient increased from 24 to 46 mmHg"],
        "hist_persistent": ["Concentric LVH"],
        "hist_new": ["Severe Symptomatic Aortic Stenosis"],
        "final_primary": "Severe Symptomatic Calcific Aortic Valve Stenosis (AVA 0.7 cm2, Vmax 4.4 m/s, Mean Gradient 46 mmHg) with Secondary Concentric LV Remodeling (LVEF 52%).",
        "final_plan": "Urgent referral to Heart Team for Transcatheter Aortic Valve Replacement (TAVR) vs Surgical Aortic Valve Replacement (SAVR). Avoid physical overexertion and vasodilators."
    },
    {
        "doctor_id": "DOC-003",
        "doctor_email": "raman@gmail.com",
        "patient_id": "PT-10493",
        "name": "Priya Patel",
        "age": 53,
        "gender": "Female",
        "medical_history_summary": "Known history of myxomatous mitral valve prolapse, presenting with sudden-onset acute dyspnea, orthopnea, and a loud 4/6 holosystolic blowing murmur radiating to the axilla.",
        "report_id": "REP-10493",
        "assessment_date": datetime.now(timezone.utc) - timedelta(hours=10),
        "ecg_finding": "Sinus tachycardia (106 bpm) with left atrial enlargement (P-mitrale in lead II) and inferior T-wave flattening.",
        "ecg_conf": 0.90,
        "ecg_evidence": ["Sinus tachycardia at 106 bpm", "Broad notched P-waves (P-mitrale duration 124 ms in lead II)", "Non-specific inferior repolarization abnormalities"],
        "echo_finding": "Severe acute Mitral Regurgitation secondary to posterior mitral leaflet (P2 segment) flail and ruptured chordae tendineae, with hyperdynamic LVEF (58%), vena contracta 0.8 cm, and systolic flow reversal in pulmonary veins.",
        "echo_conf": 0.96,
        "lvef": 58.0,
        "echo_evidence": ["Estimated LVEF: 58.0% (Hyperdynamic)", "Ruptured chordae tendineae with posterior leaflet (P2) flail into left atrium during systole", "Color Doppler: Eccentric anteriorly directed jet of severe Mitral Regurgitation (Vena contracta: 0.8 cm, EROA: 0.52 cm2)", "Systolic flow reversal documented in right superior pulmonary vein"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant acute structural valve failure: Left atrial overload on ECG correlates with mechanical posterior flail leaflet and severe mitral regurgitation.",
        "hist_rel": HistoryRelationship.NEW,
        "hist_summary": "Acute chordal rupture on background of mild chronic myxomatous mitral valve prolapse.",
        "hist_changes": ["New ruptured chordae P2 flail", "New severe mitral regurgitation", "New acute pulmonary venous flow reversal"],
        "hist_persistent": [],
        "hist_new": ["Flail Posterior Mitral Leaflet", "Severe Acute Mitral Regurgitation"],
        "final_primary": "Severe Acute Mitral Regurgitation Secondary to Ruptured Chordae Tendineae and Flail Posterior Leaflet (P2 Segment) with Preserved LV Function (LVEF 58%).",
        "final_plan": "Urgent cardiothoracic surgical consultation for minimally invasive or robotic Mitral Valve Repair (neochordae + annuloplasty ring). Medical stabilization with preload/afterload reduction."
    },

    # ==========================================
    # DOCTOR 4: Dr. Samuel Davies (sam@gmail.com / DOC-004) - Heart Failure & Transplantation
    # ==========================================
    {
        "doctor_id": "DOC-004",
        "doctor_email": "sam@gmail.com",
        "patient_id": "PT-10503",
        "name": "Oliver Queen",
        "age": 40,
        "gender": "Male",
        "medical_history_summary": "Baseline evaluation following resolution of mild post-viral syndrome. Normal exercise tolerance.",
        "report_id": "REP-10503",
        "assessment_date": datetime.now(timezone.utc) - timedelta(hours=6),
        "ecg_finding": "Normal Sinus Rhythm (66 bpm) with normal axis, intervals, and voltage.",
        "ecg_conf": 0.98,
        "ecg_evidence": ["Heart rate: 66 bpm", "Normal PR 150 ms, QRS 86 ms, QTc 404 ms", "No ST/T abnormalities"],
        "echo_finding": "Normal left ventricular dimensions (LVEDD 46 mm) and normal systolic function (LVEF 65%) with normal diastolic filling and normal BNP biomarkers.",
        "echo_conf": 0.96,
        "lvef": 65.0,
        "echo_evidence": ["Estimated LVEF: 65.0% (Preserved, Normal)", "LV end-diastolic diameter: 46 mm (Normal)", "Normal filling pressures (E/e' 6.2)"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant normal heart failure screen: Normal electrical rhythm matches preserved ventricular compliance.",
        "hist_rel": HistoryRelationship.SIMILAR,
        "hist_summary": "Completely stable and normal heart failure evaluation.",
        "hist_changes": [],
        "hist_persistent": ["Normal LVEF (65%)"],
        "hist_new": [],
        "final_primary": "Normal Cardiac Functional Evaluation — Preserved Left Ventricular Systolic and Diastolic Function (LVEF 65%).",
        "final_plan": "Normal cardiac profile. No heart failure medication required."
    },
    {
        "doctor_id": "DOC-004",
        "doctor_email": "sam@gmail.com",
        "patient_id": "PT-10494",
        "name": "Elena Rostova",
        "age": 66,
        "gender": "Female",
        "medical_history_summary": "Sudden severe crushing retrosternal chest pain and dyspnea 2 hours after acute emotional shock. Coronary angiogram showed non-obstructive coronary arteries.",
        "report_id": "REP-10494",
        "assessment_date": datetime.now(timezone.utc) - timedelta(hours=3),
        "ecg_finding": "Sinus rhythm (88 bpm) with marked, widespread, symmetric deep T-wave inversions across leads V1-V6, I, aVL with significant QTc prolongation (512 ms).",
        "ecg_conf": 0.94,
        "ecg_evidence": ["Deep giant negative T-waves (>5 mm) across precordial leads V2-V6", "Marked QTc prolongation: 512 ms", "Modest troponin elevation disproportionately high for normal coronary angiogram"],
        "echo_finding": "Classic apical ballooning pattern of Takotsubo Stress Cardiomyopathy with severe apical and mid-ventricular akinesis, hypercontractile basal segments, and reduced LVEF (36%).",
        "echo_conf": 0.95,
        "lvef": 36.0,
        "echo_evidence": ["Estimated LVEF: 36.0% (Moderately Reduced)", "Classic Takotsubo apical ballooning configuration with circular apical akinesis", "Hyperdynamic preserved contraction of basal myocardial segments", "No dynamic LVOT obstruction"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant Takotsubo stress syndrome: Giant precordial T-wave inversions and prolonged QTc align with circumferential apical ballooning on echo.",
        "hist_rel": HistoryRelationship.NEW,
        "hist_summary": "Acute reversible neurocardiogenic stress cardiomyopathy triggered by sudden severe emotional bereavement.",
        "hist_changes": ["New giant T-wave inversions", "New apical ballooning", "LVEF reduced to 36%"],
        "hist_persistent": [],
        "hist_new": ["Takotsubo Stress Cardiomyopathy", "Apical Ballooning Syndrome"],
        "final_primary": "Takotsubo (Stress-Induced / Broken Heart) Cardiomyopathy with Apical Ballooning, Deep T-Wave Inversions, and Transient Systolic Dysfunction (LVEF 36%).",
        "final_plan": "Supportive inpatient heart failure care. Initiate low-dose ACE-inhibitor and Beta-blocker. Avoid exogenous catecholamines. Schedule repeat echocardiogram in 6 weeks to confirm anticipated full recovery of LVEF."
    },
    {
        "doctor_id": "DOC-004",
        "doctor_email": "sam@gmail.com",
        "patient_id": "PT-10490",
        "name": "Chloe Dubois",
        "age": 29,
        "gender": "Female",
        "medical_history_summary": "29yo female 10 days post-viral upper respiratory illness presenting with sharp retrosternal pleuritic chest pain that improves sitting forward and worsens when supine.",
        "report_id": "REP-10490",
        "assessment_date": datetime.now(timezone.utc) - timedelta(days=1),
        "ecg_finding": "Widespread diffuse concave-upward ST-segment elevation across leads I, II, aVF, V2-V6 with PR-segment depression in lead II and reciprocal PR elevation in lead aVR.",
        "ecg_conf": 0.96,
        "ecg_evidence": ["Diffuse concave ST elevations in leads I, II, aVF, V2-V6 (1.5-2.2 mm)", "PR-segment depression in inferolateral leads (diagnostic of pericarditis)", "PR-segment elevation in lead aVR (>1.0 mm)"],
        "echo_finding": "Mild global left ventricular systolic blunting (LVEF 50%) with a small-to-moderate circumferential pericardial effusion (8 mm posterior, 6 mm anterior) without tamponade physiology.",
        "echo_conf": 0.93,
        "lvef": 50.0,
        "echo_evidence": ["Estimated LVEF: 50.0% (Mild Myocardial Involvement)", "Circumferential echo-free space representing pericardial effusion (8 mm maximal depth)", "Normal right ventricular diastolic collapse / no tamponade signs", "Elevated high-sensitivity cardiac troponin I and CRP"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant acute myopericarditis: Diffuse PR depression and concave ST elevation correlate with pericardial effusion and mild myocardial stunning.",
        "hist_rel": HistoryRelationship.NEW,
        "hist_summary": "Acute viral myopericarditis following recent respiratory infection.",
        "hist_changes": ["Diffuse concave ST elevation", "PR depression", "New pericardial effusion"],
        "hist_persistent": [],
        "hist_new": ["Acute Viral Myopericarditis", "Pericardial Effusion"],
        "final_primary": "Acute Viral Myopericarditis with Diffuse Concave ST Elevation, PR Depression, Circumferential Pericardial Effusion, and Mild Myocardial Involvement (LVEF 50%).",
        "final_plan": "Initiate high-dose anti-inflammatory therapy with Ibuprofen (600mg TID) plus Colchicine (0.5mg BID for 3 months) to prevent recurrence. Restrict strenuous physical exertion for 3-6 months."
    },
    {
        "doctor_id": "DOC-004",
        "doctor_email": "sam@gmail.com",
        "patient_id": "PT-10505",
        "name": "Amina Diallo",
        "age": 50,
        "gender": "Female",
        "medical_history_summary": "End-Stage Non-Ischemic Dilated Cardiomyopathy (NYHA Class IV). Refractory heart failure with multiple hospitalizations and inotrope dependence.",
        "report_id": "REP-10505",
        "assessment_date": datetime.now(timezone.utc) - timedelta(days=2),
        "ecg_finding": "Sinus tachycardia with complete LBBB (QRS 174 ms), severe low precordial voltages, and frequent premature ventricular complexes (PVCs).",
        "ecg_conf": 0.95,
        "ecg_evidence": ["Wide complex LBBB with QRS duration 174 ms", "Sinus tachycardia at 104 bpm", "Frequent unifocal PVCs (>15% burden)"],
        "echo_finding": "Severe spherical left ventricular dilation (LVEDD 74 mm) with end-stage global akinesis (LVEF 22%), severe functional mitral regurgitation, and right ventricular dysfunction (TAPSE 12 mm).",
        "echo_conf": 0.97,
        "lvef": 22.0,
        "echo_evidence": ["Estimated LVEF: 22.0% (End-Stage HFrEF / INTERMACS Profile 3)", "Severe LV dilation: LVEDD 74 mm, LVESD 66 mm (Spherical geometry)", "Severe functional mitral and tricuspid regurgitation", "TAPSE: 12 mm (Biventricular failure)"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant end-stage biventricular heart failure: Wide LBBB electrical delay matches profound global cavity failure.",
        "hist_rel": HistoryRelationship.CHANGED,
        "hist_summary": "Progressive refractory decompensation despite maximum tolerated quadruple GDMT.",
        "hist_changes": ["LVEF dropped from 28% to 22%", "LVEDD dilated to 74 mm", "Secondary RV failure (TAPSE 12 mm)"],
        "hist_persistent": ["Severe DCM", "Complete LBBB"],
        "hist_new": ["End-Stage Biventricular Failure", "Inotrope Dependence"],
        "final_primary": "End-Stage Non-Ischemic Dilated Cardiomyopathy (NYHA IV, INTERMACS 3, LVEF 22%) with Biventricular Failure for Advanced Mechanical Support / Heart Transplant.",
        "final_plan": "Admit to Cardiac Intensive Care Unit on Milrinone inotrope infusion. Complete formal evaluation for Left Ventricular Assist Device (LVAD - HeartMate 3) as bridge to Orthotopic Heart Transplantation (OHT)."
    },
    {
        "doctor_id": "DOC-004",
        "doctor_email": "sam@gmail.com",
        "patient_id": "PT-10506",
        "name": "Margaret Kim",
        "age": 74,
        "gender": "Female",
        "medical_history_summary": "Remote anterior and inferior myocardial infarctions, progressive cardiac cachexia, severe exertional dyspnea at rest (NYHA IV).",
        "report_id": "REP-10506",
        "assessment_date": datetime.now(timezone.utc) - timedelta(days=3),
        "ecg_finding": "Poor R-wave progression with extensive QS complexes in V1-V5 and inferior leads, indicative of massive multi-vessel myocardial scar.",
        "ecg_conf": 0.94,
        "ecg_evidence": ["Extensive QS complexes across V1-V5 and II, III, aVF", "Low precordial voltage", "Secondary repolarization abnormalities"],
        "echo_finding": "Advanced ischemic cardiomyopathy with extensive anterior, apical, and inferior wall thinning, severe systolic failure (LVEF 25%), and elevated pulmonary artery systolic pressure (PASP 55 mmHg).",
        "echo_conf": 0.95,
        "lvef": 25.0,
        "echo_evidence": ["Estimated LVEF: 25.0% (Severe Ischemic Failure)", "Multi-segmental scar and severe hypokinesis/akinesis", "Pulmonary artery systolic pressure: 55 mmHg (Moderate-severe secondary PH)", "Elevated filling pressures (E/e' 22)"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant multi-territory ischemic cardiomyopathy: Widespread electrical necrosis matches extensive multi-wall mechanical scar.",
        "hist_rel": HistoryRelationship.PERSISTENT,
        "hist_summary": "Severe chronic ischemic heart failure with secondary pulmonary hypertension.",
        "hist_changes": ["PASP increased to 55 mmHg"],
        "hist_persistent": ["Severe multi-vessel scar", "LVEF 25%"],
        "hist_new": ["Secondary Pulmonary Hypertension"],
        "final_primary": "Severe Ischemic Cardiomyopathy (LVEF 25%, NYHA IV) with Multi-Territory Myocardial Scar and Secondary Pulmonary Hypertension.",
        "final_plan": "Intensify decongestion with loop diuretic (Furosemide IV) and Thiazide. Continue SGLT2 inhibitor (Dapagliflozin) and ARNI. Heart Failure disease management and palliative cardiology symptom-relief alignment."
    },

    # ==========================================
    # DOCTOR 5: Dr. David Miller (david@gmail.com / DOC-005) - Cardiothoracic & Minimally Invasive Surgery
    # ==========================================
    {
        "doctor_id": "DOC-005",
        "doctor_email": "david@gmail.com",
        "patient_id": "PT-10504",
        "name": "Rajesh Sharma",
        "age": 58,
        "gender": "Male",
        "medical_history_summary": "Type 2 diabetes, hypertension, severe multi-vessel CAD. Presented with acute crescendo angina, diaphoresis, and rest dyspnea.",
        "report_id": "REP-10504",
        "assessment_date": datetime.now(timezone.utc) - timedelta(hours=7),
        "priority_level": "critical",
        "clinical_priority": "CRITICAL — Urgent Surgical Revascularization (CABG)",
        "suspected_condition": "Critical Acute Anterior STEMI & Multi-Vessel CAD",
        "ecg_finding": "Acute Anterior-Lateral ST-Elevation Myocardial Infarction (STEMI) with ST elevation up to 4.2 mm in V1-V6, I, aVL, and reciprocal inferior depression (II, III, aVF).",
        "ecg_conf": 0.98,
        "ecg_evidence": ["Marked ST elevation in V1-V4 (up to 4.2 mm) and I, aVL", "Reciprocal ST depression in leads III and aVF (>2.0 mm)", "Developing pathological anterior Q-waves"],
        "echo_finding": "Severely depressed left ventricular systolic pump function (LVEF 28%) with extensive anterior, septal, and apical akinesis, and elevated pulmonary pressure (PASP 46 mmHg).",
        "echo_conf": 0.96,
        "lvef": 28.0,
        "echo_evidence": ["Estimated LVEF: 28.0% (Severely Reduced, Acute HFrEF)", "Extensive anterior, apical, and septal wall akinesis", "PASP: 46 mmHg (Secondary Pulmonary Hypertension)", "Elevated LV filling pressures (E/e' 22)"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant acute transmural multi-territory ischemia: Extensive anterior-lateral ST elevation directly matches severe mechanical apical/anterior akinesis (LVEF 28%).",
        "hist_rel": HistoryRelationship.NEW,
        "hist_summary": "Acute catastrophic progression of coronary artery disease requiring urgent surgical CABG revascularization.",
        "hist_changes": ["New ST elevation V1-V6", "New anterior/apical akinesis", "LVEF dropped to 28%"],
        "hist_persistent": [],
        "hist_new": ["Acute Anterior-Lateral STEMI", "Severe Ischemic Cardiomyopathy (LVEF 28%)"],
        "final_primary": "Critical Acute Anterior-Lateral STEMI with Severe Systolic Heart Failure (LVEF 28%) and Triple-Vessel CAD Scheduled for Urgent CABG x 3.",
        "final_plan": "Admit directly to Coronary Care Unit / Cardiothoracic Surgical ICU for Urgent Coronary Artery Bypass Grafting (CABG x 3: LIMA-LAD, SVG-OM, SVG-PDA). Heparinization, DAPT, and IABP hemodynamic support."
    },
    {
        "doctor_id": "DOC-005",
        "doctor_email": "david@gmail.com",
        "patient_id": "PT-10507",
        "name": "Michael Chen",
        "age": 61,
        "gender": "Male",
        "medical_history_summary": "Bicuspid aortic valve, severe calcific stenosis. Presented with exertional syncope, angina during minimal walking, and NYHA III-IV dyspnea.",
        "report_id": "REP-10507",
        "assessment_date": datetime.now(timezone.utc) - timedelta(days=1),
        "priority_level": "critical",
        "clinical_priority": "CRITICAL — Urgent Surgical Valve Replacement (SAVR/TAVR)",
        "suspected_condition": "Critical Calcific Aortic Valve Stenosis",
        "ecg_finding": "Severe Left Ventricular Hypertrophy with high Sokolow-Lyon voltage (4.6 mV) and prominent downsloping ST-T strain in leads I, aVL, V5, V6.",
        "ecg_conf": 0.96,
        "ecg_evidence": ["Sokolow-Lyon voltage > 4.6 mV", "Pronounced lateral repolarization strain pattern", "First-degree AV block (PR 210 ms)"],
        "echo_finding": "Critical Calcific Aortic Valve Stenosis with AVA 0.58 cm2, peak velocity 4.85 m/s, peak gradient 92 mmHg, mean gradient 56 mmHg, and concentric LVH (LVEF 48%).",
        "echo_conf": 0.98,
        "lvef": 48.0,
        "echo_evidence": ["Estimated LVEF: 48.0% (Concentric Remodeling)", "Aortic Valve Area: 0.58 cm2 (<0.8 cm2 critical stenosis)", "Peak transvalvular velocity: 4.85 m/s", "Mean pressure gradient: 56 mmHg (Severe gradient)", "Heavily calcified, immobilized aortic leaflets"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant critical valvular stenosis: High transaortic gradient (56 mmHg mean) corresponds directly to severe electrical LVH strain.",
        "hist_rel": HistoryRelationship.CHANGED,
        "hist_summary": "Critical progression of aortic stenosis requiring immediate surgical intervention.",
        "hist_changes": ["AVA reduced to 0.58 cm2", "Mean gradient 56 mmHg"],
        "hist_persistent": ["Severe LVH"],
        "hist_new": ["Critical Calcific Aortic Stenosis"],
        "final_primary": "Critical Calcific Aortic Stenosis (AVA 0.58 cm2, Peak Velocity 4.85 m/s, Mean Gradient 56 mmHg) Scheduled for Surgical Aortic Valve Replacement (SAVR/TAVR).",
        "final_plan": "Admit for Urgent Surgical Aortic Valve Replacement (SAVR with bioprosthetic valve) or TAVR depending on STS risk score calculation. Preoperative coronary angiography and CT TAVR protocol mapping."
    },
    {
        "doctor_id": "DOC-005",
        "doctor_email": "david@gmail.com",
        "patient_id": "PT-10508",
        "name": "Sunita Verma",
        "age": 64,
        "gender": "Female",
        "medical_history_summary": "Myxomatous mitral valve disease, developed acute chordal rupture 48 hours prior. Presented with acute flash pulmonary edema, orthopnea, and severe dyspnea.",
        "report_id": "REP-10508",
        "assessment_date": datetime.now(timezone.utc) - timedelta(hours=12),
        "priority_level": "critical",
        "clinical_priority": "CRITICAL — Urgent Mitral Valve Repair",
        "suspected_condition": "Acute Severe Mitral Regurgitation (P2 Flail Leaflet)",
        "ecg_finding": "Sinus tachycardia (114 bpm) with prominent P-mitrale left atrial overload (130 ms) and secondary repolarization abnormalities.",
        "ecg_conf": 0.94,
        "ecg_evidence": ["Sinus tachycardia at 114 bpm", "P-mitrale in lead II (130 ms)", "Inferolateral repolarization strain"],
        "echo_finding": "Critical acute severe Mitral Regurgitation with ruptured primary chordae to P2 scallop, systolic leaflet flail into left atrium, vena contracta 0.88 cm, regurgitant fraction 64%, and elevated PASP 54 mmHg.",
        "echo_conf": 0.97,
        "lvef": 56.0,
        "echo_evidence": ["Estimated LVEF: 56.0% (Hyperdynamic)", "Ruptured chordae tendineae with severe P2 posterior leaflet flail", "Vena contracta: 0.88 cm, Regurgitant fraction: 64%", "Elevated pulmonary artery pressure: 54 mmHg"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant acute structural surgical pathology: Severe mitral regurgitation jet correlates with left atrial strain and hemodynamic overload.",
        "hist_rel": HistoryRelationship.NEW,
        "hist_summary": "Acute chordal rupture requiring urgent surgical mitral reconstruction.",
        "hist_changes": ["New P2 flail leaflet", "New severe MR (64% regurgitant fraction)"],
        "hist_persistent": [],
        "hist_new": ["Flail Posterior Mitral Leaflet", "Critical Mitral Regurgitation"],
        "final_primary": "Critical Acute Severe Mitral Regurgitation Secondary to Ruptured Chordae Tendineae and P2 Flail Leaflet for Urgent Robotic / Minimally Invasive Mitral Valve Repair.",
        "final_plan": "Schedule for Urgent Minimally Invasive / Robotic Mitral Valve Repair (Gore-Tex artificial neochordae reconstruction + Physio II annuloplasty ring). Intraoperative transesophageal echocardiography (TEE) guidance."
    },
    {
        "doctor_id": "DOC-005",
        "doctor_email": "david@gmail.com",
        "patient_id": "PT-10509",
        "name": "David Miller",
        "age": 69,
        "gender": "Male",
        "medical_history_summary": "Type 2 diabetes mellitus, peripheral artery disease, severe triple-vessel CAD, 40 pack-year smoking. Presented with resting angina and diaphoresis.",
        "report_id": "REP-10509",
        "assessment_date": datetime.now(timezone.utc) - timedelta(days=2),
        "priority_level": "critical",
        "clinical_priority": "CRITICAL — Urgent Triple CABG Revascularization",
        "suspected_condition": "Critical Left Main & Triple-Vessel CAD",
        "ecg_finding": "Widespread horizontal ST-segment depression in leads I, II, aVF, V3-V6 with reciprocal ST elevation in lead aVR (>1.8 mm), indicating Left Main / Multi-Vessel subendocardial ischemia.",
        "ecg_conf": 0.96,
        "ecg_evidence": ["ST elevation in lead aVR: 1.8 mm (>1.0 mm diagnostic of Left Main / proximal LAD)", "Diffuse ST depression across 8 leads (I, II, aVF, V3-V6)", "Inverted T-waves in lateral leads"],
        "echo_finding": "Moderately reduced left ventricular systolic function (LVEF 38%) with extensive basal-inferior, lateral, and posterior wall hypokinesis, and elevated filling pressures.",
        "echo_conf": 0.94,
        "lvef": 38.0,
        "echo_evidence": ["Estimated LVEF: 38.0% (Moderately Reduced)", "Basal-inferior, posterior, and lateral wall hypokinesis", "Preserved apical contractility"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant Left Main / Multi-vessel ischemic pattern: ST elevation in aVR matches diffuse multi-territory wall motion hypokinesis.",
        "hist_rel": HistoryRelationship.NEW,
        "hist_summary": "New presentation of critical multi-vessel CAD with high-grade Left Main stenosis.",
        "hist_changes": ["New ST elevation in aVR", "New lateral hypokinesis"],
        "hist_persistent": [],
        "hist_new": ["Left Main & Triple-Vessel CAD", "Multi-Territory Ischemia"],
        "final_primary": "Critical Left Main & Triple-Vessel Coronary Artery Disease with Global Subendocardial Ischemia (LVEF 38%) Scheduled for Urgent Coronary Artery Bypass Grafting (CABG x 3).",
        "final_plan": "Urgent inpatient Coronary Artery Bypass Grafting (CABG x 3: LIMA to LAD, SVG to OM, SVG to PDA). Intra-aortic balloon pump (IABP) standby."
    },
    {
        "doctor_id": "DOC-005",
        "doctor_email": "david@gmail.com",
        "patient_id": "PT-10510",
        "name": "Anita Patel",
        "age": 52,
        "gender": "Female",
        "medical_history_summary": "Severe drug-refractory Hypertrophic Obstructive Cardiomyopathy (HOCM) with resting LVOT gradient 88 mmHg and recurrent exertional syncope.",
        "report_id": "REP-10510",
        "assessment_date": datetime.now(timezone.utc) - timedelta(days=3),
        "priority_level": "critical",
        "clinical_priority": "CRITICAL — Surgical Morrow Septal Myectomy",
        "suspected_condition": "Severe Drug-Refractory Obstructive HOCM (LVOT 88 mmHg)",
        "ecg_finding": "Marked voltage LVH with giant precordial voltages and deep dagger-like septal Q-waves in lateral leads I, aVL, V5, V6.",
        "ecg_conf": 0.95,
        "ecg_evidence": ["Deep dagger Q-waves in lateral leads", "Precordial voltage sum > 5.2 mV", "Giant positive T-waves V2-V4"],
        "echo_finding": "Severe asymmetric septal hypertrophy (IVS thickness 24.5 mm) with severe dynamic Left Ventricular Outflow Tract obstruction (resting gradient 88 mmHg, Valsalva gradient 120 mmHg), SAM, and hyperdynamic LVEF (70%).",
        "echo_conf": 0.97,
        "lvef": 70.0,
        "echo_evidence": ["Estimated LVEF: 70.0% (Hyperdynamic)", "Interventricular septal thickness: 24.5 mm (Severe hypertrophy)", "Resting LVOT peak gradient: 88 mmHg (>50 mmHg surgical indication)", "Severe Systolic Anterior Motion (SAM) with septal contact"],
        "fusion_status": FusionStatus.AGREEMENT,
        "fusion_summary": "Concordant severe obstructive HOCM: Septal dagger Q-waves align with 24.5 mm asymmetric hypertrophy and 88 mmHg peak gradient.",
        "hist_rel": HistoryRelationship.PERSISTENT,
        "hist_summary": "Refractory HOCM with severe gradient persistent despite high-dose Beta-blocker and Disopyramide therapy.",
        "hist_changes": ["Resting LVOT gradient increased to 88 mmHg"],
        "hist_persistent": ["Asymmetric septal hypertrophy (24.5 mm)", "SAM"],
        "hist_new": ["Surgical Septal Myectomy Indication"],
        "final_primary": "Critical Drug-Refractory Hypertrophic Obstructive Cardiomyopathy (IVS 24.5 mm, Peak LVOT Gradient 88 mmHg, Recurrent Syncope) Scheduled for Surgical Transaortic Morrow Septal Myectomy.",
        "final_plan": "Schedule for Surgical Transaortic Morrow Septal Myectomy with concomitant subvalvular mitral apparatus resection. Intraoperative TEE to confirm elimination of LVOT gradient and SAM."
    }
]

async def seed_sample_data():
    patient_repo = PatientRepository()
    report_repo = ReportRepository()
    
    logger.info(f"Seeding exactly 5 cases per doctor for all 5 doctors (Total: {len(DOCTOR_PATIENT_CASES)} cases)... ")
    
    for case in DOCTOR_PATIENT_CASES:
        p_schema = PatientSchema(
            patient_id=case["patient_id"],
            name=case["name"],
            age=case["age"],
            gender=case["gender"],
            medical_history_summary=case["medical_history_summary"],
            assigned_doctor_id=case["doctor_id"],
            assigned_doctor_email=case["doctor_email"]
        )
        await patient_repo.create_patient(p_schema)
        
        rep_schema = OmniHealthReportSchema(
            report_id=case["report_id"],
            patient_id=case["patient_id"],
            assessment_date=case["assessment_date"],
            assigned_doctor_id=case["doctor_id"],
            assigned_doctor_email=case["doctor_email"],
            ecg_analysis=ECGEvidenceSchema(
                finding=case["ecg_finding"],
                confidence=case["ecg_conf"],
                supporting_evidence=case["ecg_evidence"],
                model_name="ECG-CNN-PTB-XL",
                model_version="v0.1.0",
                limitations=["AI-assisted analysis; verify with 12-lead tracing"],
                heart_rate=68 if "Normal" in case["ecg_finding"] else (118 if "Fibrillation" in case["ecg_finding"] else 84),
                pr_interval=154 if "Normal" in case["ecg_finding"] else 180,
                qrs_duration=88 if "Normal" in case["ecg_finding"] else (142 if "Conduction" in case["ecg_finding"] or "Bundle" in case["ecg_finding"] else 96),
                qtc_interval=412 if "Normal" in case["ecg_finding"] else 448,
                rhythm_type="Normal Sinus" if "Normal" in case["ecg_finding"] else "Pathological Pattern",
            ),
            echo_analysis=EchoEvidenceSchema(
                finding=case["echo_finding"],
                confidence=case["echo_conf"],
                evidence=case["echo_evidence"],
                model_name="EchoNet-Dynamic-3DCNN",
                model_version="v0.1.0",
                limitations=["Apical 4-chamber ultrasound geometry"]
            ),
            fusion_result=FusionResultSchema(
                status=case["fusion_status"],
                agreement_summary=case["fusion_summary"],
                combined_evidence=case["ecg_evidence"] + case["echo_evidence"]
            ),
            history_analysis=HistoryAnalysisSchema(
                relationship=case["hist_rel"],
                current_summary=case["hist_summary"],
                changes_detected=case["hist_changes"],
                persistent_findings=case["hist_persistent"],
                new_findings=case["hist_new"],
                analysis_notes="Longitudinal comparison evaluated against baseline."
            ),
            final_assessment=FinalAssessmentSchema(
                primary_assessment=case["final_primary"],
                suspected_condition=case.get("suspected_condition", case["final_primary"]),
                clinical_priority=case.get("clinical_priority", "CRITICAL — Urgent Inpatient Care" if case.get("priority_level") == "critical" else ("ROUTINE — Outpatient Follow-up" if "Normal" in case["final_primary"] else "HIGH — Clinical Intervention")),
                priority_level=case.get("priority_level", "critical" if case.get("doctor_id") == "DOC-005" else ("routine" if "Normal" in case["final_primary"] else "high")),
                supported_findings=[
                    f"ECG: {case['ecg_finding']}",
                    f"Echo: {case['echo_finding']}",
                    f"Fusion: {case['fusion_summary']}"
                ],
                ecg_evidence_summary=case["ecg_finding"],
                echo_evidence_summary=case["echo_finding"],
                historical_evidence_summary=case["hist_summary"],
                cross_modal_analysis=case["fusion_summary"],
                explanation=case["final_plan"],
                limitations=["AI-assisted clinical decision support prototype."],
                evidence_sufficiency="sufficient",
                requires_clinical_review=True
            ),
            pipeline_version="0.1.0"
        )
        await report_repo.save_report(rep_schema)
        
    logger.info(f"Successfully seeded {len(DOCTOR_PATIENT_CASES)} doctor-assigned clinical cases.")

# Alias for backward compatibility
seed_all_sample_patients = seed_sample_data

